[general]
import = [
  "~/AppData/Roaming/alacritty/ubuntu.toml",
  "~/AppData/Roaming/alacritty/dark_pride.toml",
]
working_directory = "None"
live_config_reload = true


[window]
dimensions = { columns = 75, lines = 25 }
position = { x = 800, y = 200 }           # has no effect on Wayland
padding = { x = 0, y = 0 }
dynamic_padding = false
decorations = "Full"                      # None, Full 边框和标题栏
opacity = 1
blur = true
startup_mode = "Windowed"
title = "Windows Terminal"
dynamic_title = false
decorations_theme_variant = "Light"       # Dark, Light, None 设置标题栏颜色


[scrolling]
history = 10000
multiplier = 3


[font] # RobotoMono-NF, IntelOneMono-NF(IntoneMono)
normal = { family = "RobotoMono Nerd Font", style = "Regular" } # Regular, Light
bold   = { family = "RobotoMono Nerd Font", style = "Bold"    }
italic = { family = "RobotoMono Nerd Font", style = "Italic"  }
size = 14
offset = { x = 1, y = 0 }       # x 修改字符间距，y修改行间距
glyph_offset = { x = 0, y = 0 } # 增大 x 字形向右移动，增大 y 字形向上移动


[colors]
cursor = { text = "#000000", cursor = "#ff8f5f" }
footer_bar = { foreground = "#ff8f5f", background = "#000000" }


[bell]
animation = "Linear"
duration = 3         # 闪烁时间，0为禁用
color = "#ffffff"
command = "None"     # bell 被出发就执行这里的命令


[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true


[terminal]
shell = { program = "pwsh", args = ["-l"] }


[mouse]
hide_when_typing = true
bindings = [
  { mouse = "Right", action = "Paste" },
  { mouse = "Left",  action = "Copy"  },
]


[[hints.enabled]]
action = "copy"
binding = { key = "h", mods = "Alt" }
regex = "[a-f0-9]{6,}"

[[hints.enabled]]
# command = "xdg-open" # on linux/bsd
# command = "open" # on macos
command = { program = "cmd", args = ["/c", "start", ""] } # on windows
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "e", mods = "Alt" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001f\u007f-\u009f<>\"\\s{-}\\^⟨⟩`]+"

[keyboard]
# mode = "appcursor" | "appkeypad" | "search" | "Alt" | "vi"
bindings = [
  { key = "Enter", mods = "Alt", action = "ToggleFullscreen" },
  { key = "b", mods = "Alt", action = "Minimize" },
  { key = "n", mods = "Alt", action = "ToggleMaximized" },
  { key = "m", mods = "Alt", action = "ToggleMaximized" },
  { key = "n", mods = "Control|Shift", action = "CreateNewWindow" },
  { key = " ", mods = "Control|Shift", action = "ToggleViMode" },

  # search
  { key = "h", mods = "Control|Shift|Alt", mode = "Search", action = "CreateNewWindow" },

  # vi
  { key = "o", mode = "vi", action = "Open" },
]
