[general]
import = [
  "~/AppData/Roaming/alacritty/dark_pride.toml",
  "~/AppData/Roaming/alacritty/seashells.toml",
  "~/AppData/Roaming/alacritty/solarized_light.toml",
  "~/AppData/Roaming/alacritty/ubuntu.toml",
]
live_config_reload = true
working_directory = "None"

[terminal.shell]
program = "pwsh"
args = ["-l"]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold   = { family = "FiraCode Nerd Font", style = "Bold"    }
italic = { family = "FiraCode Nerd Font", style = "Italic"  }

size = 13

[window]
dimensions = { columns = 75, lines = 25 }
position = { x = 800, y = 200 }
startup_mode = "Windowed"
title = "Putty"
dynamic_title = false
decorations_theme_variant = "None"
decorations = "Full"                      # None, Full
opacity = 0.8
blur = true

[scrolling]
history = 10000
multiplier = 3

[colors]
cursor = { text = "#000000", cursor = "#ff8f5f" }
footer_bar = { foreground = "#ff8f5f", background = "#000000" }

[bell]
animation = "Linear"
duration = 0

[[hints.enabled]]
action = "Copy"
binding = { key = "h", mods = "alt" }
regex = "[a-f0-9]{6,}"

[[hints.enabled]]
# command = "xdg-open" # On Linux/BSD
# command = "open" # On macOS
command = { program = "cmd", args = ["/c", "start", ""] }                                                                                                 # On Windows
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "e", mods = "alt" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

[keyboard]
# mode = "AppCursor" | "AppKeypad" | "Search" | "Alt" | "Vi"
bindings = [
  { key = "Enter", mods = "alt", action = "ToggleFullscreen" },
  { key = "b", mods = "alt", action = "Minimize" },
  { key = "n", mods = "alt", action = "ToggleMaximized" },
  { key = "m", mods = "alt", action = "ToggleMaximized" },
  { key = "n", mods = "Control|Shift", action = "CreateNewWindow" },
  { key = " ", mods = "Control|Shift", action = "ToggleViMode" },

  # Search
  { key = "h", mods = "Control|Shift|Alt", mode = "Search", action = "CreateNewWindow" },

  # Vi
  { key = "o", mode = "Vi", action = "Open" },
]
